# data 관련 설정
image_root: /data/ephemeral/home/data/train/DCM
label_root: /data/ephemeral/home/data/train/outputs_json

# 모델명 및 사전 학습 여부
model_name: UnetPlusPlus
model_parameter:
  encoder_name: efficientnet-b3
  classes: 29

# batch_size (4 or 2) 고정
train_batch_size: 2
val_batch_size: 4

# val_num_worker 지정
num_workers: 4

# image resize 2048로 고정
image_size: &image_size 2048

# transform 관련
train_transform:
  Resize:
    width: *image_size
    height: *image_size
  RandomBrightnessContrast:
    brightness_limit: 0.2
    contrast_limit: 0.1
    p: 0.7
  ElasticTransform:
    alpha: 15.0
    sigma: 2.0
    p: 0.5
  Blur:
    blur_limit: 3
    p: 0.2
  HorizontalFlip:
    p: 0.5

val_transform:
  Resize:
    width: *image_size
    height: *image_size

# 학습 관련 하이퍼파라미터
lr: 1e-3
weight_decay: 1e-6

max_epoch: &max_epoch 80

# loss 관련 설정
loss_name: Combined

# 단일 loss 사용시에 필요한 parameter -> dict 형태로 작성
# loss_parameter: {}

# combo loss 사용시
loss_parameter:
  losses:
    - name: BCEWithLogitsLoss
      weight: 0.5
      params: {}
    - name: JaccardLoss
      weight: 0.5
      params:
        smooth: 1e-5
    - name: DiceLoss
      weight: 0.5
      params:
        smooth: 1e-5

# scheduler 관련 설정
scheduler_name: ReduceLROnPlateau

# scheduler 필요한 parameter -> dict 형태로 작성
scheduler_parameter:
  mode: max
  factor: 0.5
  patience: 1
  threshold: 0.005
  threshold_mode: abs
  min_lr: 1e-6

# random seed값
seed: 42

# validation 관련 인자 2번 폴드로 고정
val_fold: 2
val_interval: 5
threshold: 0.5

# checkpoint 저장 경로
save_dir: ./checkpoints/Baseline

# wandb
api_key: api 키를 입력해주세요
team_name: CV_12_Segmantation
project_name: Second Hypothesis
experiment_detail: 실험 detail 입력 # 숫자, 문자, -, _, . 만 가능 (space 불가)

# notion
# server_id는 서버0, 1, 2, 3
# experiment_description는 무슨 작업 하는지 줄 띄기는 \n 사용하면 됩니다
# user_name은 본인 이름 넣으시면 됩니다
server_id: 서버N
experiment_description: experiment
user_name: 이름
