# data 관련 설정
image_root: /data/ephemeral/home/data/train/DCM
label_root: /data/ephemeral/home/data/train/outputs_json

# 모델명 및 사전 학습 여부
model_name: fcn_resnet50
pretrained: True

# batch_size
train_batch_size: 8
val_batch_size: 4

# 학습 관련 하이퍼파라미터
lr: 1e-4
weight_decay: 1e-6

max_epoch: 100

# random seed값
seed: 42

# validation 관련 인자
val_fold: 0
val_interval: 5
threshold: 0.5

# checkpoint 저장 경로
save_dir: ./checkpoints/fcn_resnet50

# transform 관련
transform:
  Resize:
    width: 512
    height: 512