# data 관련 설정
image_root: /data/ephemeral/home/data/train/DCM
label_root: /data/ephemeral/home/data/train/outputs_json

# 모델명 및 사전 학습 여부
model_name: Unet
model_parameter:
  encoder_name: efficientnet-b0
  classes: 29

# batch_size
train_batch_size: 4
val_batch_size: 4

# image resize
image_size: &image_size 512

# transform 관련
transform:
  Resize:
    width: *image_size
    height: *image_size

# 학습 관련 하이퍼파라미터
lr: 1e-3
weight_decay: 1e-6

max_epoch: &max_epoch 20

# loss 관련 설정 
loss_name: Combined

# 단일 loss 사용시에 필요한 parameter -> dict 형태로 작성
# loss_parameter: {}

# combo loss 사용시
loss_parameter:
  losses:
    - name: BCEWithLogitsLoss
      weight: 0.5
      params: {}
    - name: JaccardLoss
      weight: 0.5
      params:
        smooth: 1e-5
    - name: DiceLoss
      weight: 0.5
      params:
        smooth: 1e-5
        

# scheduler 관련 설정
scheduler_name: ReduceLROnPlateau

# scheduler 필요한 parameter -> dict 형태로 작성
scheduler_parameter: 
  mode: max
  factor: 0.5
  patience: 1
  threshold: 0.005
  threshold_mode: abs
  min_lr: 1e-6

# random seed값
seed: 42

# validation 관련 인자
val_fold: 2
val_interval: 2
threshold: 0.5

# checkpoint 저장 경로
save_dir: ./checkpoints/Unet

# wandb
api_key: apikey를 입력해주세요
team_name: CV_12_Segmantation
project_name: 실험의 큰 주제
experiment_detail: 실험 명

# notion
# server_id는 서버0, 1, 2, 3
# experiment_description는 무슨 작업 하는지 줄 띄기는 \n 사용하면 됩니다
# user_name은 본인 이름 넣으시면 됩니다
server_id: 서버N
experiment_description: 실험 설명
user_name: 이름