# data 관련 설정
image_root: /data/ephemeral/home/data/train/DCM
label_root: /data/ephemeral/home/data/train/outputs_json

# 모델명 및 사전 학습 여부
model_name: Unet
model_parameter:
  encoder_name: efficientnet-b0
  classes: 29

# batch_size
train_batch_size: 2
val_batch_size: 4

# image resize
image_size: &image_size 512

# transform 관련
transform:
  Resize:
    width: *image_size
    height: *image_size

# 학습 관련 하이퍼파라미터
lr: 1e-3
weight_decay: 1e-6

max_epoch: &max_epoch 2

# loss 관련 설정 
loss_name: Combined

# 단일 loss 사용시에 필요한 parameter -> dict 형태로 작성
# loss_parameter: {}

# combo loss 사용시
loss_parameter:
  losses:
    - name: BCEWithLogitsLoss
      weight: 0.5
      params: {}
    - name: JaccardLoss
      weight: 0.5
      params:
        smooth: 1e-5
    - name: DiceLoss
      weight: 0.5
      params:
        smooth: 1e-5
        

# scheduler 관련 설정
scheduler_name: CosineAnnealingLR

# scheduler 필요한 parameter -> dict 형태로 작성
scheduler_parameter: 
  T_max: *max_epoch

# random seed값
seed: 42

# validation 관련 인자
val_fold: 0
val_interval: 1
threshold: 0.5

# checkpoint 저장 경로
save_dir: ./checkpoints/Unet

# wandb
api_key: 6719c512ca92adae09770aafb128622b6cdf145d
team_name: CV_12_Segmantation
project_name: Swin Unet 실험
experiment_detail: swin unet epoch10 val5

# notion
# server_id는 서버0, 1, 2, 3
# experiment_description는 무슨 작업 하는지 줄 띄기는 \n 사용하면 됩니다
# user_name은 본인 이름 넣으시면 됩니다
server_id: 서버2
experiment_description: Swin Unet 실험중
user_name: 재만