# data 관련 설정
image_root: /data/ephemeral/home/data/train/DCM
label_root: /data/ephemeral/home/data/train/outputs_json

# 모델명 및 사전 학습 여부
model_name: fcn_resnet50
pretrained: True

# batch_size
train_batch_size: 8
val_batch_size: 4

# image resize
image_size: &image_size 512

# transform 관련
transform:
  Resize:
    width: *image_size
    height: *image_size

# 학습 관련 하이퍼파라미터
lr: 1e-4
weight_decay: 1e-6

max_epoch: 100

# random seed값
seed: 42

# validation 관련 인자
val_fold: 0
val_interval: 5
threshold: 0.5

# checkpoint 저장 경로
save_dir: ./checkpoints/fcn_resnet50

# wandb
api_key: wandb 개인 key 작성
team_name: CV_12_Segmantation
project_name: initial project
experiment_detail: relogin test
